### ISSUE TITLE
Equipment Manager 

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI_Bunny#1]
First off, AWESOME add-on! Love the newer character frame layout!

![wowscrnshot_092115_204127](https://cloud.githubusercontent.com/assets/7307335/10009370/48646dfc-60a1-11e5-9c08-dcae1bc1afa7.jpg)

**Comment by Bunny67** [comment]
There is a newer version, but has not yet been updated, it is necessary to finish something.
