### ISSUE TITLE
Character Mount Highlight

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI_Bunny#10]
c60f13affa2e56e2f1bfebf03da58c32052cf778

First off, thank you! This is an awesome update!

When I am mounted, the current mount becomes highlighted. I do not think it is supposed to do that on retail?

![world of warcraft 8_31_2016 1_07_12 pm](https://cloud.githubusercontent.com/assets/7307335/18140650/120bca62-6f7c-11e6-8e2c-54d9cf92f49e.png)

**Comment by Bunny67** [comment]
https://github.com/ElvUI/ElvUI_Bunny/commit/b624abd4b3fd6b1333805623a0435d7489b35420 ?

**Comment by crumdidlyumshis** [comment]
Thank you!
