### ISSUE TITLE
Character Frame - Retail-like functionality

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI_Bunny#2]
In retail wow, the frame centers the title and the x moved to the right side of the frame.

![wowscrnshot_092115_205931](https://cloud.githubusercontent.com/assets/7307335/10009615/6bc65c3e-60a5-11e5-8b0e-2350b4e7a92e.jpg)

**Comment by Bunny67** [comment]
The same will be fixed :)
