### ISSUE TITLE
Character menu

### ISSUE THREAD

**Issue by ExeBack** [ElvUI/ElvUI_Bunny#5]
![ss 2015-12-07 at 09 25 36](https://cloud.githubusercontent.com/assets/16203314/11649825/ba29a548-9d8b-11e5-9253-5e32dc8135b6.jpg)
soo this happens to me :D

**Comment by Bunny67** [comment]
I do not understand what the problem is (

**Comment by ExeBack** [comment]
It doesn't show more than half of the stats

**Comment by Bunny67** [comment]
Right now normal or still?

**Comment by ExeBack** [comment]
it doesn't show.

**Comment by Bunny67** [comment]
What to do before you broke? Since I still have a couple, and people are okay
![wowscrnshot_120815_172928](https://cloud.githubusercontent.com/assets/5816685/11658042/90861898-9dd1-11e5-88a4-a24489e963b6.jpg)

**Comment by ExeBack** [comment]
Okay, I fixed it ;) had to change my UI's scale. Ty

**Comment by ExeBack** [comment]
Btw maybe u could make extraElvUIactionbars? :D

**Comment by crumdidlyumshis** [comment]
Fixed and close?

**Comment by ExeBack** [comment]
Yep, sorry for not replying :/
